repos:
  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate message format
        entry: .github/hooks/validate-commit-msg.sh
        language: script
        stages: [commit-msg]
